name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download zashboard
        run: |
          curl --connect-timeout 5 --progress-bar -L -o dist.zip "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"
          mv dist.zip atun/

      - name: Download core
        run: |
          gh release download "Prerelease-Alpha" --repo "MetaCubeX/mihomo" --pattern "*android-arm64-v8*" --output mihomo-android-arm64.gz
          gh release download --repo "reF1nd/sing-box-releases" --pattern "*android-arm64*" --output sing-box-android-arm64.tar.gz
          gzip -dc mihomo-android-arm64.gz > mihomo && rm -f mihomo-android-arm64.gz
          mkdir tmpggh
          tar -zxvf sing-box-android-arm64.tar.gz -C tmpggh --strip-components=1 && mv tmpggh/sing-box sing-box && rm -rf tmpggh
          zip core.zip mihomo sing-box
          mv core.zip atun/

      - name: Run build.sh
        run: sh build.sh

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: atun_*.zip
          generate_release_notes: true

      - name: Upload file to Telegram
        uses: xireiki/channel-post@v2
        with:
          chat_id: "${{ secrets.CHAT_ID }}"
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          path: atun_*.zip
          context: "大人，有更新啦！"
          parse_mode: HTML
          api_id: ${{ secrets.API_ID }}
          api_hash: ${{ secrets.API_HASH }}
          method: sendFile
